//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawnshop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PawnshopEntities : DbContext
    {
        public PawnshopEntities()
            : base("name=PawnshopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Employess> Employess { get; set; }
        public virtual DbSet<MonthlyPayments> MonthlyPayments { get; set; }
        public virtual DbSet<Passports> Passports { get; set; }
        public virtual DbSet<PaymentsStatusTypes> PaymentsStatusTypes { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductsSells> ProductsSells { get; set; }
        public virtual DbSet<ProductsTypes> ProductsTypes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
