//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawnshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyPayments
    {
        public int MonthlyPaymentID { get; set; }
        public int ProductID { get; set; }
        public double Amount { get; set; }
        public System.DateTime DeadlineDate { get; set; }
        public System.DateTime ActualDate { get; set; }
        public int EmployeeID { get; set; }
        public int PaymentStatusTypeID { get; set; }
    
        public virtual Employess Employess { get; set; }
        public virtual PaymentsStatusTypes PaymentsStatusTypes { get; set; }
        public virtual Products Products { get; set; }
    }
}
